---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      service_facts:

    - name: Ensure ssh is running
      assert:
        that: (ansible_facts.services.ssh is defined) and (ansible_facts.services.ssh.state == 'running')

    - name: Ensure SSH Settings are proper
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^{{ item }}"
        line: "{{ item }}"
        state: present
      check_mode: yes
      register: conf
      with_items:
        - "PasswordAuthentication no"
        - "PermitRootLogin no"
        - "Port 22"
        - "PermitTunnel no"
      failed_when: (conf is changed) or (conf is failed)
